name: Elixir Compatibility Matrix
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test - OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        # See https://hexdocs.pm/elixir/1.13/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        otp: ["23.x", "26.x", "27.x"]
        elixir: ["1.14.x", "1.17.x", "1.18.x"]
        exclude:
          # OTP 23
          - elixir: "1.15.x"
            otp: "23.x"
          - elixir: "1.17.x"
            otp: "23.x"
          - elixir: "1.18.x"
            otp: "23.x"
          # OTP 26 
          # - Users on recent elixir likely updated OTP versions
          - elixir: "1.18.x"
            otp: "26.x"
          # OTP 27 - Elixir 1.14.x is not compatible with OTP 27
          - elixir: "1.14.x"
            otp: "27.x"
          

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Retrieve Build Cache
        uses: actions/cache@v4
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test --exclude integration
